timeout: 0

/DragonOS
    protocol: limine
    path: boot():/boot/dragonos.bin
    resolution: 1024x768
    framebuffer_resolution: 1024x768
    module_path: boot():/boot/doom1.wad
    module_path: boot():/boot/wallpaper.bmp
    module_path: boot():/boot/test.lua
    module_path: boot():/boot/test.c
